<a href="https://colab.research.google.com/github/AshwinCarvalho999/Book-Recommendation-System/blob/main/Book_Recommendation_System_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Book** **Recommendation** **System**.

Book Recommendation System using Keras
A recommendation system seeks to predict the rating or preference a user would give to an item given his old item ratings or preferences. Recommendation systems are used by pretty much every major company in order to enhance the quality of their services.
Content:

Loading in data

Creating dot product model

Creating Neural Network

Visualizing Embeddings

Making Recommendations

In [ ]:
#importing the important libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import warnings

from keras.layers import Input, Embedding, Flatten, Dot, Dense
from keras.models import Model

warnings.filterwarnings('ignore')
%matplotlib inline

In [ ]:
#importing datasets
users=pd.read_csv('/content/drive/MyDrive/Book Recommendation System capstone project/Users.csv')
books = pd.read_csv('/content/drive/MyDrive/Book Recommendation System capstone project/Books.csv')
rating=pd.read_csv('/content/drive/MyDrive/Book Recommendation System capstone project/Ratings.csv')

In [ ]:
books.head()

ISBN  ...                                        Image-URL-L
0  0195153448  ...  http://images.amazon.com/images/P/0195153448.0...
1  0002005018  ...  http://images.amazon.com/images/P/0002005018.0...
2  0060973129  ...  http://images.amazon.com/images/P/0060973129.0...
3  0374157065  ...  http://images.amazon.com/images/P/0374157065.0...
4  0393045218  ...  http://images.amazon.com/images/P/0393045218.0...

[5 rows x 8 columns]

In [ ]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')

In [ ]:
#selecting the features
books=books[['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher']]

In [ ]:
books.head()

ISBN  ...                   Publisher
0  0195153448  ...     Oxford University Press
1  0002005018  ...       HarperFlamingo Canada
2  0060973129  ...             HarperPerennial
3  0374157065  ...        Farrar Straus Giroux
4  0393045218  ...  W. W. Norton &amp; Company

[5 rows x 5 columns]

In [ ]:
 #changing the column names in books
books.rename(columns={'Book-Title':'title','Book-Author':'author','Year-Of-Publication':'year','Publisher':'publisher'},inplace=True)

In [ ]:
books.head()

ISBN  ...                   publisher
0  0195153448  ...     Oxford University Press
1  0002005018  ...       HarperFlamingo Canada
2  0060973129  ...             HarperPerennial
3  0374157065  ...        Farrar Straus Giroux
4  0393045218  ...  W. W. Norton &amp; Company

[5 rows x 5 columns]

In [ ]:
users.head()

User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [ ]:
 #changing the column names in users
 users.rename(columns={'User-ID':'user_id','Location':'location','Age':'age'},inplace=True) 

In [ ]:
users.head()

user_id                            location   age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [ ]:
rating.head()

User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [ ]:
#changing the column names in rating
rating.rename(columns={'User-ID':'user_id','Book-Rating':'rating'},inplace=True)

In [ ]:
rating.head()

user_id        ISBN  rating
0   276725  034545104X       0
1   276726  0155061224       5
2   276727  0446520802       0
3   276729  052165615X       3
4   276729  0521795028       6

In [ ]:
books.shape

(271360, 5)

In [ ]:
users.shape

(278858, 3)

In [ ]:
rating.shape

(1149780, 3)

In [ ]:
#unique users
rating['user_id'].value_counts().shape

(105283,)

In [ ]:
#considering those users who have viewed more than 200 books
x=rating['user_id'].value_counts()>200

In [ ]:
x[x].shape

(899,)

In [ ]:
y=x[x].index

In [ ]:
rating=rating[rating['user_id'].isin(y)]

In [ ]:
rating.shape

(526356, 3)

In [ ]:
#those users who have viewed more than 200 books with there rating on books
rating_with_books=rating.merge(books,on='ISBN')

In [ ]:
rating_with_books.shape

(487671, 7)

In [ ]:
# total rating of a book 
number_rating=rating_with_books.groupby('title')['rating'].count().reset_index()

In [ ]:
#changing the column names
number_rating.rename(columns={'rating':'number of rating'},inplace=True) 

In [ ]:
number_rating.head()

title  number of rating
0   A Light in the Storm: The Civil War Diary of ...                 2
1                              Always Have Popsicles                 1
2               Apple Magic (The Collector's series)                 1
3   Beyond IBM: Leadership Marketing and Finance ...                 1
4   Clifford Visita El Hospital (Clifford El Gran...                 1

In [ ]:
final_ratings=rating_with_books.merge(number_rating,on='title') 

In [ ]:
final_ratings.head()

user_id        ISBN  ...                  publisher number of rating
0   277427  002542730X  ...  John Wiley &amp; Sons Inc               82
1     3363  002542730X  ...  John Wiley &amp; Sons Inc               82
2    11676  002542730X  ...  John Wiley &amp; Sons Inc               82
3    12538  002542730X  ...  John Wiley &amp; Sons Inc               82
4    13552  002542730X  ...  John Wiley &amp; Sons Inc               82

[5 rows x 8 columns]

In [ ]:
final_ratings.shape

(487671, 8)

In [ ]:
# considering those books which has got more than 50 ratings 
final_ratings=final_ratings[final_ratings['number of rating']>=50]

In [ ]:
final_ratings.shape

(61853, 8)

In [ ]:
# droping the same record from final ratings
final_ratings.drop_duplicates(['user_id','title'],inplace=True)

In [ ]:
final_ratings.shape

(59850, 8)

In [ ]:
# pivot table
book_pivot=final_ratings.pivot_table(columns='user_id',index='title',values='rating') 

In [ ]:
book_pivot.shape

(742, 888)

In [ ]:
book_pivot.fillna(0,inplace=True)

In [ ]:
book_pivot

user_id                                             254     ...  278418
title                                                       ...        
1984                                                   9.0  ...     0.0
1st to Die: A Novel                                    0.0  ...     0.0
2nd Chance                                             0.0  ...     0.0
4 Blondes                                              0.0  ...     0.0
84 Charing Cross Road                                  0.0  ...     0.0
...                                                    ...  ...     ...
Year of Wonders                                        0.0  ...     0.0
You Belong To Me                                       0.0  ...     0.0
Zen and the Art of Motorcycle Maintenance: An I...     0.0  ...     0.0
Zoya                                                   0.0  ...     0.0
\O\" Is for Outlaw"                                    0.0  ...     0.0

[742 rows x 888 columns]

In [ ]:
from scipy.sparse import csr_matrix
book_sparse=csr_matrix(book_pivot)

In [ ]:
type(book_sparse)

scipy.sparse.csr.csr_matrix

In [ ]:
from sklearn.neighbors import NearestNeighbors
model=NearestNeighbors(algorithm='brute') 

In [ ]:
model.fit(book_sparse)

NearestNeighbors(algorithm='brute', leaf_size=30, metric='minkowski',
                 metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                 radius=1.0)

In [ ]:
book_pivot.iloc[237,:].values.reshape(1,-1)

array([[ 9.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  8.,  0.,  0.,  0.,  0.,  0.,  0.,
         8.,  0.,  0.,  8.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         9.,  0.,  0.,  0., 10.,  0.,  0., 10.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  7.,  9.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  8.,  0.,  0.,  0.,  0.,  0.,  0.,  9.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  8.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.

In [ ]:
distances,suggestions=model.kneighbors(book_pivot.iloc[54,:].values.reshape(1,-1))

In [ ]:
distances

array([[ 0.        , 42.34383072, 43.48562981, 43.50861984, 43.56604182]])

In [ ]:
# recommendation
suggestions 

array([[ 54, 184, 291, 440, 393]])

In [ ]:
for i in range(len(suggestions)):
    print(book_pivot.index[suggestions[i]])

Index(['Animal Farm', 'Exclusive', 'Jacob Have I Loved', 'Second Nature',
       'Pleading Guilty'],
      dtype='object', name='title')


In [ ]:
def reco(book_name):
    book_id=np.where(book_pivot.index==book_name)[0][0]
    distances,suggestions=model.kneighbors(book_pivot.iloc[book_id,:].values.reshape(1,-1))
    
    
    
    for i in range(len(suggestions)):
        if i==0:
            print("the suggestions are ",book_name,"are : ")
        if not i:
            print(book_pivot.index[suggestions[i]])

In [ ]:
reco('Animal Farm')

the suggestions are  Animal Farm are : 
Index(['Animal Farm', 'Exclusive', 'Jacob Have I Loved', 'Second Nature',
       'Pleading Guilty'],
      dtype='object', name='title')
